"""Data quality and leakage audit generators."""

import logging
import pathlib

import pandas as pd

logger = logging.getLogger(__name__)


def _series_to_md(s: pd.Series, col_name: str = "Category") -> str:
    lines = [f"| {col_name} | Count | Share |", "|---|---|---|"]
    tot = int(s.sum())
    for k, v in s.items():
        pct = (v / tot) * 100 if tot > 0 else 0
        lines.append(f"| `{k}` | {v:,} | {pct:.2f}% |")
    return "\n".join(lines)


def generate_data_quality_report(
    raw_df: pd.DataFrame,
    cohort_df: pd.DataFrame,
    flow: dict,
    output_path: str = "reports/data_quality.md",
) -> None:
    """Generates comprehensive data quality audit report."""
    p = pathlib.Path(output_path)
    p.parent.mkdir(parents=True, exist_ok=True)

    missing_data = []
    for col in raw_df.columns:
        q_count = int((raw_df[col] == "?").sum())
        na_count = int(raw_df[col].isna().sum())
        tot = q_count + na_count
        if tot > 0:
            missing_data.append({
                "column": col,
                "missing_count": tot,
                "missing_pct": (tot / len(raw_df)) * 100,
                "symbol": "?" if q_count > 0 else "NaN",
            })
    missing_df = pd.DataFrame(missing_data).sort_values("missing_count", ascending=False)
    missing_rows_md = ""
    for _, r in missing_df.iterrows():
        missing_rows_md += f"| `{r['column']}` | {r['missing_count']:,} | {r['missing_pct']:.2f}% | `{r['symbol']}` |\n"

    raw_target = raw_df["readmitted"].value_counts()
    cohort_prev = flow["readmit_30d_prevalence"] * 100

    race_table = _series_to_md(cohort_df["race"].value_counts(dropna=False), "Race Group")
    gender_table = _series_to_md(cohort_df["gender"].value_counts(dropna=False), "Gender")
    age_table = _series_to_md(cohort_df["age"].value_counts(dropna=False), "Age Interval")

    md = f"""# Data Quality Audit Report

Dataset: **UCI Diabetes 130-US Hospitals (1999-2008)**

## 1. High-Level Ingestion Statistics
- **Raw Encounters**: {len(raw_df):,}
- **Raw Unique Patients**: {raw_df['patient_nbr'].nunique():,}
- **Total Columns**: {len(raw_df.columns)}
- **Filtered Primary Cohort**: {len(cohort_df):,} patients (one index encounter per patient, excluding expired/hospice)
- **Primary Cohort 30-Day Readmission Prevalence**: **{cohort_prev:.2f}%** ({flow['readmit_30d_positives']:,} positives)

---

## 2. Raw Target Distribution (`readmitted`)

| Class | Meaning | Raw Count | Raw Share | Cohort Mapping (`readmit_30d`) |
|---|---|---|---|---|
| `<30` | Readmitted within 30 days | {raw_target.get('<30', 0):,} | {(raw_target.get('<30', 0)/len(raw_df))*100:.2f}% | **1 (Positive Class)** |
| `>30` | Readmitted after 30 days | {raw_target.get('>30', 0):,} | {(raw_target.get('>30', 0)/len(raw_df))*100:.2f}% | **0 (Negative Class)** |
| `NO` | Not readmitted within window | {raw_target.get('NO', 0):,} | {(raw_target.get('NO', 0)/len(raw_df))*100:.2f}% | **0 (Negative Class)** |

---

## 3. Missing Value Audit

Missingness in this dataset is predominantly encoded as `?`.

| Column | Missing Count | Missing % | Missing Representation |
|---|---|---|---|
{missing_rows_md}

### Key Missingness Decisions
- **`weight` (96.86% missing)**: Dropped entirely.
- **`payer_code` (39.56% missing)**: Missing mapped to explicit `'Unknown'` class.
- **`medical_specialty` (49.08% missing)**: Grouped into top frequent specialties + `'Unknown'` and `'Other'`.
- **`race` (2.23% missing)**: Preserved as `'Unknown'` in audit attribute (audit only, not model feature).
- **`diag_1/2/3`**: Missing values mapped to `'Unknown'` within ICD-9 taxonomy.

---

## 4. Constant Feature Audit

| Column | Distinct Values | Distribution | Decision |
|---|---|---|---|
| `examide` | 1 | 100% 'No' | Dropped (zero variance) |
| `citoglipton` | 1 | 100% 'No' | Dropped (zero variance) |

---

## 5. Demographics in Primary Cohort

### Race Distribution (Audit Attribute)
{race_table}

### Gender Distribution (Audit Attribute)
{gender_table}

### Age Distribution
{age_table}

---
*Report generated by `src/readmit/audit.py`.*
"""
    p.write_text(md, encoding="utf-8")
    logger.info(f"Saved data quality report to {output_path}")


def generate_leakage_audit_report(output_path: str = "reports/leakage_audit.md") -> None:
    """Generates comprehensive leakage audit report adhering to Invariant 1."""
    p = pathlib.Path(output_path)
    p.parent.mkdir(parents=True, exist_ok=True)

    md = """# Clinical Leakage Audit & Feature Eligibility

**Prediction Point Invariant**: Point of discharge.
**Core Test**: *"Would the care team know this feature at discharge?"*

## Column-by-Column Classification

| Column Name | Category | Role | Justification / Prediction Point Status |
|---|---|---|---|
| `encounter_id` | **C** | Identifier | Unique encounter identifier; dropped from features. |
| `patient_nbr` | **C** | Identifier | Unique patient identifier; strictly used for grouped splitting. |
| `readmitted` | **C** | Target | The outcome being predicted (`<30` vs `>30`/`NO`). Dropped from features. |
| `race` | **C / Audit** | Protected Attribute | Audited for algorithmic fairness across demographic groups. Excluded from features. |
| `gender` | **C / Audit** | Protected Attribute | Audited for parity across male/female subgroups. Excluded from features. |
| `weight` | **C** | Unreliable / Missing | 96.86% missing; unreliably documented. Dropped. |
| `examide` | **C** | Constant | 100% 'No' across all encounters. Dropped (zero variance). |
| `citoglipton` | **C** | Constant | 100% 'No' across all encounters. Dropped (zero variance). |
| `age` | **A** | Feature (Numeric/Band) | Known at admission/discharge. Midpoint used for modeling; 4-band group used for fairness audit. |
| `admission_type_id` | **A** | Categorical | Emergency vs Urgent vs Elective. Known at admission. Grouped. |
| `discharge_disposition_id` | **A** | Categorical | Destination at discharge (Home, SNF, Home Health, etc.). Finalized at discharge. |
| `admission_source_id` | **A** | Categorical | Referral source (Physician, Emergency Room, Transfer). Known at admission. |
| `time_in_hospital` | **A** | Numeric | Length of stay in days. Known at discharge. |
| `payer_code` | **B** | Categorical | Financial coverage / payer. Known at admission; proxy for socioeconomic status. Explicit 'Unknown'. |
| `medical_specialty` | **B** | Categorical | Specialty of admitting physician. Known during stay; grouped + 'Unknown'. |
| `num_lab_procedures` | **A** | Numeric | Total lab tests performed during stay. Cumulative count finalized at discharge. |
| `num_procedures` | **A** | Numeric | Non-lab procedures during stay. Finalized at discharge. |
| `num_medications` | **A** | Numeric | Distinct medications administered during stay. Finalized at discharge. |
| `number_outpatient` | **A** | Numeric | Outpatient visits in preceding 12 months. Prior utilization known from EHR history. |
| `number_emergency` | **A** | Numeric | Emergency room visits in preceding 12 months. Prior utilization known from EHR history. |
| `number_inpatient` | **A** | Numeric | Inpatient admissions in preceding 12 months. Strong historical utilization marker. |
| `diag_1` | **A** | Categorical | Primary diagnosis ICD-9 code. Coded at discharge; grouped into 9 clinical categories. |
| `diag_2` | **A** | Categorical | Secondary diagnosis ICD-9 code. Grouped into clinical taxonomy. |
| `diag_3` | **A** | Categorical | Additional secondary diagnosis ICD-9 code. Grouped into clinical taxonomy. |
| `number_diagnoses` | **A** | Numeric | Total diagnoses entered into encounter billing record. Finalized at discharge. |
| `max_glu_serum` | **A** | Categorical/Binary | Maximum glucose serum test result during stay (`>200`, `>300`, `norm`, `none`). |
| `A1Cresult` | **A** | Categorical/Binary | Hemoglobin A1c test result (`>8`, `>7`, `norm`, `none`). Measured during inpatient episode. |
| 23 Medication Columns | **A** | Categorical/Counts | Specific diabetes medications. Summarized into active meds, changes (Up/Down), steady meds. |
| `change` | **A** | Binary | Change in diabetic medications during encounter. Known at discharge. |
| `diabetesMed` | **A** | Binary | Whether any diabetic medication was prescribed. Known at discharge. |

---

## Invariant Adherence
- **Zero Patient Overlap**: Ensured by patient-level splitting in `data.py`.
- **Target Independence**: Target (`readmit_30d`) is completely isolated and never enters the transformation pipeline.
- **Audit Attributes Isolated**: `race_group` and `gender` are stripped before feature transformation and only attached during fairness evaluation.
"""
    p.write_text(md, encoding="utf-8")
    logger.info(f"Saved leakage audit report to {output_path}")